# Generated by Django 3.2.7 on 2021-11-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cartproduct_final_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='Composition',
            new_name='composition',
        ),
        migrations.RenameField(
            model_name='sushi',
            old_name='Composition',
            new_name='composition',
        ),
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
